using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;

namespace Store.Views.Filtering
{
    /// <summary>
    /// Ставит фильтр в шапку уже после того, как базовый грид записал свой Header.
    /// </summary>
    public static class ColumnCheckFilterBehavior
    {
        public static readonly DependencyProperty IsEnabledProperty = DependencyProperty.RegisterAttached(
            "IsEnabled",
            typeof(bool),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(false, OnIsEnabledChanged));

        public static readonly DependencyProperty HeaderTemplateProperty = DependencyProperty.RegisterAttached(
            "HeaderTemplate",
            typeof(DataTemplate),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(null, OnHeaderTemplateChanged));

        public static bool GetIsEnabled(DependencyObject obj) => (bool)obj.GetValue(IsEnabledProperty);

        public static void SetIsEnabled(DependencyObject obj, bool value) => obj.SetValue(IsEnabledProperty, value);

        public static DataTemplate GetHeaderTemplate(DependencyObject obj) => (DataTemplate)obj.GetValue(HeaderTemplateProperty);

        public static void SetHeaderTemplate(DependencyObject obj, DataTemplate value) => obj.SetValue(HeaderTemplateProperty, value);

        private static readonly DependencyProperty ColumnsHandlerProperty = DependencyProperty.RegisterAttached(
            "ColumnsHandler",
            typeof(NotifyCollectionChangedEventHandler),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(null));

        private static readonly DependencyProperty OriginalHeaderProperty = DependencyProperty.RegisterAttached(
            "OriginalHeader",
            typeof(object),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(null));

        private static readonly DependencyProperty OriginalHeaderHeightProperty = DependencyProperty.RegisterAttached(
            "OriginalHeaderHeight",
            typeof(double),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(double.NaN));

        private static readonly List<WeakReference> Grids = new List<WeakReference>();
        private static bool _watchingThemes;

        private static void OnIsEnabledChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var grid = d as DataGrid;
            if (grid == null)
                return;

            if ((bool)e.NewValue)
            {
                grid.Loaded += OnLoaded;
                grid.AutoGeneratedColumns += OnAutoGeneratedColumns;
                grid.DataContextChanged += OnDataContextChanged;
                var handler = new NotifyCollectionChangedEventHandler((sender, args) => Schedule(grid));
                grid.SetValue(ColumnsHandlerProperty, handler);
                grid.Columns.CollectionChanged += handler;
                Remember(grid);
                WatchThemes();
                Schedule(grid);
            }
            else
            {
                grid.Loaded -= OnLoaded;
                grid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
                grid.DataContextChanged -= OnDataContextChanged;
                var handler = grid.GetValue(ColumnsHandlerProperty) as NotifyCollectionChangedEventHandler;
                if (handler != null)
                    grid.Columns.CollectionChanged -= handler;
                grid.ClearValue(ColumnsHandlerProperty);
            }
        }

        private static void OnHeaderTemplateChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) => Schedule(d as DataGrid);

        private static void OnLoaded(object sender, RoutedEventArgs e) => Schedule((DataGrid)sender);

        private static void OnAutoGeneratedColumns(object sender, EventArgs e) => Schedule((DataGrid)sender);

        private static void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e) => Schedule((DataGrid)sender);

        private static void Schedule(DataGrid grid)
        {
            if (grid == null)
                return;

            grid.Dispatcher.BeginInvoke(DispatcherPriority.ApplicationIdle, new Action(() => Apply(grid)));
        }

        private static void Apply(DataGrid grid)
        {
            var template = GetHeaderTemplate(grid);
            var filters = ResolveFilters(grid.DataContext);
            if (template == null || filters == null)
                return;

            if (!IsModernTheme(grid))
            {
                RestoreHeaders(grid);
                return;
            }

            if (double.IsNaN((double)grid.GetValue(OriginalHeaderHeightProperty)))
                grid.SetValue(OriginalHeaderHeightProperty, grid.ColumnHeaderHeight);
            if (double.IsNaN(grid.ColumnHeaderHeight) || grid.ColumnHeaderHeight < 64)
                grid.ColumnHeaderHeight = 64;

            foreach (var column in grid.Columns)
            {
                if (column.Header is ContentControl existing && existing.Content is ColumnHeaderFilter)
                    continue;

                var filter = filters.Find(column.SortMemberPath);
                if (filter == null)
                    filter = filters.FindByTitle(column.Header as string);
                if (filter == null)
                    continue;

                if (!(column.Header is ContentControl))
                    column.SetValue(OriginalHeaderProperty, column.Header);

                column.HeaderTemplate = null;
                column.Header = new ContentControl
                {
                    Content = filter,
                    ContentTemplate = template,
                    Focusable = false,
                    VerticalAlignment = VerticalAlignment.Top
                };
            }
        }

        private static void RestoreHeaders(DataGrid grid)
        {
            foreach (var column in grid.Columns)
            {
                var control = column.Header as ContentControl;
                if (control == null || !(control.Content is ColumnHeaderFilter))
                    continue;

                var original = column.GetValue(OriginalHeaderProperty);
                column.Header = original ?? ((ColumnHeaderFilter)control.Content).Title;
            }

            var height = (double)grid.GetValue(OriginalHeaderHeightProperty);
            if (!double.IsNaN(height))
                grid.ColumnHeaderHeight = height;
        }

        private static bool IsModernTheme(FrameworkElement element)
        {
            return string.Equals(element.TryFindResource("Store.CurrentTheme") as string, "Modern", StringComparison.Ordinal);
        }

        private static void Remember(DataGrid grid)
        {
            for (var i = Grids.Count - 1; i >= 0; i--)
            {
                var existing = Grids[i].Target as DataGrid;
                if (existing == null || ReferenceEquals(existing, grid))
                    Grids.RemoveAt(i);
            }

            Grids.Add(new WeakReference(grid));
        }

        private static void WatchThemes()
        {
            if (_watchingThemes || Application.Current == null)
                return;

            _watchingThemes = true;
            Application.Current.Resources.MergedDictionaries.CollectionChanged += (sender, args) =>
            {
                foreach (var reference in Grids.ToArray())
                {
                    var grid = reference.Target as DataGrid;
                    if (grid != null)
                        Schedule(grid);
                }
            };
        }

        private static ColumnHeaderFilterSet ResolveFilters(object dataContext)
        {
            if (dataContext == null)
                return null;

            var property = dataContext.GetType().GetProperty("HeaderFilters", BindingFlags.Instance | BindingFlags.Public);
            return property == null ? null : property.GetValue(dataContext, null) as ColumnHeaderFilterSet;
        }
    }
}
