using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;

namespace Store.Views.Filtering
{
    /// <summary>
    /// После автогенерации колонок ставит в шапку шаблон с фильтром.
    /// Базовый DataGrid не меняется. Шаблон задаётся в разметке экрана,
    /// потому что там объявлен Controls3:MultiSelectComboBox.
    /// </summary>
    public static class ColumnCheckFilterBehavior
    {
        public static readonly DependencyProperty IsEnabledProperty = DependencyProperty.RegisterAttached(
            "IsEnabled",
            typeof(bool),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(false, OnIsEnabledChanged));

        public static readonly DependencyProperty HeaderTemplateProperty = DependencyProperty.RegisterAttached(
            "HeaderTemplate",
            typeof(DataTemplate),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(null, OnHeaderTemplateChanged));

        public static bool GetIsEnabled(DependencyObject obj) => (bool)obj.GetValue(IsEnabledProperty);

        public static void SetIsEnabled(DependencyObject obj, bool value) => obj.SetValue(IsEnabledProperty, value);

        public static DataTemplate GetHeaderTemplate(DependencyObject obj) => (DataTemplate)obj.GetValue(HeaderTemplateProperty);

        public static void SetHeaderTemplate(DependencyObject obj, DataTemplate value) => obj.SetValue(HeaderTemplateProperty, value);

        private static void OnIsEnabledChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var grid = d as DataGrid;
            if (grid == null)
                return;

            if ((bool)e.NewValue)
            {
                grid.Loaded += OnLoaded;
                grid.AutoGeneratedColumns += OnAutoGeneratedColumns;
                grid.DataContextChanged += OnDataContextChanged;
                Schedule(grid);
            }
            else
            {
                grid.Loaded -= OnLoaded;
                grid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
                grid.DataContextChanged -= OnDataContextChanged;
            }
        }

        private static void OnHeaderTemplateChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            Schedule(d as DataGrid);
        }

        private static void OnLoaded(object sender, RoutedEventArgs e) => Schedule((DataGrid)sender);

        private static void OnAutoGeneratedColumns(object sender, EventArgs e) => Schedule((DataGrid)sender);

        private static void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e) => Schedule((DataGrid)sender);

        private static void Schedule(DataGrid grid)
        {
            if (grid == null)
                return;

            grid.Dispatcher.BeginInvoke(DispatcherPriority.Loaded, new Action(() => Apply(grid)));
        }

        private static void Apply(DataGrid grid)
        {
            var template = GetHeaderTemplate(grid);
            var host = grid.DataContext as IColumnHeaderFilterHost;
            if (template == null || host == null)
                return;

            if (grid.ColumnHeaderHeight < 64)
                grid.ColumnHeaderHeight = 64;

            foreach (var column in grid.Columns)
            {
                var textColumn = column as DataGridTextColumn;
                if (textColumn == null || string.IsNullOrEmpty(textColumn.SortMemberPath))
                    continue;

                var filter = host.Find(textColumn.SortMemberPath);
                if (filter == null || ReferenceEquals(textColumn.Header, filter))
                    continue;

                textColumn.Header = filter;
                textColumn.HeaderTemplate = template;
            }
        }
    }
}
