using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace Store.Views.Filtering
{
    /// <summary>
    /// Вешается на грид в разметке экрана. Базовые DataGrid и ItemsViewModel не меняются.
    /// </summary>
    public static class ColumnCheckFilterBehavior
    {
        public static readonly DependencyProperty IsEnabledProperty = DependencyProperty.RegisterAttached(
            "IsEnabled",
            typeof(bool),
            typeof(ColumnCheckFilterBehavior),
            new PropertyMetadata(false, OnIsEnabledChanged));

        public static bool GetIsEnabled(DependencyObject obj) => (bool)obj.GetValue(IsEnabledProperty);

        public static void SetIsEnabled(DependencyObject obj, bool value) => obj.SetValue(IsEnabledProperty, value);

        private static void OnIsEnabledChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var grid = d as DataGrid;
            if (grid == null)
                return;

            if ((bool)e.NewValue)
            {
                grid.AutoGeneratedColumns += OnAutoGeneratedColumns;
                grid.DataContextChanged += OnDataContextChanged;
                Attach(grid);
            }
            else
            {
                grid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
                grid.DataContextChanged -= OnDataContextChanged;
            }
        }

        private static void OnAutoGeneratedColumns(object sender, System.EventArgs e) => Attach((DataGrid)sender);

        private static void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e) => Attach((DataGrid)sender);

        private static void Attach(DataGrid grid)
        {
            var host = grid.DataContext as IColumnCheckFilterHost;
            if (host == null)
                return;

            var view = grid.ItemsSource as ICollectionView;
            if (view == null && grid.ItemsSource != null)
                view = CollectionViewSource.GetDefaultView(grid.ItemsSource);
            host.ColumnFilters.Bind(view);

            foreach (var column in grid.Columns)
            {
                var textColumn = column as DataGridTextColumn;
                if (textColumn == null || string.IsNullOrEmpty(textColumn.SortMemberPath))
                    continue;
                if (textColumn.Header is FrameworkElement)
                    continue;

                var title = textColumn.Header as string ?? textColumn.SortMemberPath;
                textColumn.Header = host.ColumnFilters.Get(textColumn.SortMemberPath, title).CreateHeader();
            }
        }
    }
}
